module.exports = [
  {
    GUID: "721653",
    Name: "HandTrigger",
    Transform: {
      posX: 38,
      posY: 4,
      posZ: -42,
      rotX: 0.0,
      rotY: 0.0,
      rotZ: 0.0,
      scaleX: 19,
      scaleY: 7,
      scaleZ: 9
    },
    Nickname: "",
    Description: "",
    GMNotes: "",
    ColorDiffuse: {
      r: 0.856,
      g: 0.09999997,
      b: 0.09399996,
      a: 0.0
    },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: true,
    Grid: false,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    HideWhenFaceDown: false,
    Hands: false,
    FogColor: "Red",
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: ""
  },
  {
    GUID: "65cea9",
    Name: "HandTrigger",
    Transform: {
      posX: 38,
      posY: 4,
      posZ: 42,
      rotX: 0.0,
      rotY: 180,
      rotZ: 0.0,
      scaleX: 19,
      scaleY: 7,
      scaleZ: 9
    },
    Nickname: "",
    Description: "",
    GMNotes: "",
    ColorDiffuse: {
      r: 0.117999978,
      g: 0.53,
      b: 1.0,
      a: 0.0
    },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: true,
    Grid: false,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    HideWhenFaceDown: false,
    Hands: false,
    FogColor: "Blue",
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: ""
  },
  {
    GUID: "65cea7",
    Name: "HandTrigger",
    Transform: {
      posX: -28,
      posY: 4,
      posZ: -42,
      rotX: 0,
      rotY: 0,
      rotZ: 0.0,
      scaleX: 19,
      scaleY: 7,
      scaleZ: 9
    },
    Nickname: "",
    Description: "",
    GMNotes: "",
    ColorDiffuse: {
      r: 0.117999978,
      g: 1.0,
      b: 0.53,
      a: 0.0
    },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: true,
    Grid: false,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    HideWhenFaceDown: false,
    Hands: false,
    FogColor: "Green",
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: ""
  },
  {
    GUID: "65cea6",
    Name: "HandTrigger",
    Transform: {
      posX: -54,
      posY: 4,
      posZ: -42,
      rotX: 0,
      rotY: 0,
      rotZ: 0.0,
      scaleX: 19,
      scaleY: 7,
      scaleZ: 9
    },
    Nickname: "",
    Description: "",
    GMNotes: "",
    ColorDiffuse: {
      r: 1.0,
      g: 0.117999978,
      b: 1.0,
      a: 0.0
    },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: true,
    Grid: false,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    HideWhenFaceDown: false,
    Hands: false,
    FogColor: "Purple",
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: ""
  },
];
