const hiddenBagsZone = {
  GUID: "5e7847",
  Name: "FogOfWarTrigger",
  Transform: {
    posX: -17,
    posY: 3.515223,
    posZ: 31.8327522,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 36.3627625,
    scaleY: 5.1,
    scaleZ: 10.7926264
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 0.24999997,
    g: 0.24999997,
    b: 0.24999997,
    a: 0.75
  },
  Tags: [
    "hidden_zone"
  ],
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  FogColor: "Black",
  FogHidePointers: false,
  FogReverseHiding: false,
  FogSeethrough: true,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const cardSelectZone = {
  GUID: "d9c954",
  Name: "ScriptingTrigger",
  Transform: {
    posX: -57,
    posY: 3.5,
    posZ: 20.8,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 36,
    scaleY: 5.1,
    scaleZ: 33
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const paginationZone = {
  GUID: "84d9b3",
  Name: "ScriptingTrigger",
  Transform: {
    posX: -57,
    posY: 3.51,
    posZ: 0,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const redDeckZone = {
  GUID: "4116d5",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 55.61447,
    posY: 3.52000022,
    posZ: -10.08176,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 5.330105,
    scaleY: 5.1,
    scaleZ: 7.492021
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const redResourceZone = {
  GUID: "442907",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 37.56571,
    posY: 3.52000022,
    posZ: -25.3071918,
    rotX: 0.0,
    rotY: 0.49980098,
    rotZ: 0.0,
    scaleX: 27.9480133,
    scaleY: 5.1,
    scaleZ: 22.43542
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const redTrashZone = {
  GUID: "5ec481",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 55.75614,
    posY: 3.52000022,
    posZ: -17.5985279,
    rotX: 0.0,
    rotY: 359.6668,
    rotZ: 0.0,
    scaleX: 5.91755152,
    scaleY: 5.1,
    scaleZ: 6.65405273
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const blueDeckZone = {
  GUID: "8a3626",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 20.3896465,
    posY: 3.52000022,
    posZ: 10.234211,
    rotX: 0.0,
    rotY: 181.260757,
    rotZ: 0.0,
    scaleX: 6.257269,
    scaleY: 5.1,
    scaleZ: 7.107547
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const blueResourseZone = {
  GUID: "3612da",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 38.2983627,
    posY: 3.52000022,
    posZ: 25.7074356,
    rotX: 0.0,
    rotY: 180.5942,
    rotZ: 0.0,
    scaleX: 28.7466583,
    scaleY: 5.1,
    scaleZ: 23.0969429
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const blueTrashZone = {
  GUID: "2bb5fc",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 20.312685,
    posY: 3.52000022,
    posZ: 17.71481,
    rotX: 0.0,
    rotY: 179.905273,
    rotZ: 0.0,
    scaleX: 6.099278,
    scaleY: 5.1,
    scaleZ: 7.11145353
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

const fieldZone = {
  GUID: "924f57",
  Name: "ScriptingTrigger",
  Transform: {
    posX: 37.859375,
    posY: 3.52000022,
    posZ: 0.0704083443,
    rotX: 0.0,
    rotY: 359.5002,
    rotZ: 0.0,
    scaleX: 27.420763,
    scaleY: 5.1,
    scaleZ: 27.7764282
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  ColorDiffuse: {
    r: 1.0,
    g: 1.0,
    b: 1.0,
    a: 0.509803951
  },
  Tags: [
    "BlueCard",
    "RedCard"
  ],
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: ""
};

module.exports = [
  hiddenBagsZone,
  cardSelectZone,
  paginationZone,
  redDeckZone,
  redResourceZone,
  redTrashZone,
  blueDeckZone,
  blueResourseZone,
  blueTrashZone,
  fieldZone,
];
